### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by SK0RM** [markdirish/node-odbc#16]
Hello,

I am trying to install the package but `npm i odbc` fail with the following message:

```
> odbc@2.0.0-3 install /my_project_path/node_modules/odbc
> node-gyp configure build

  CXX(target) Release/obj.target/odbc/src/odbc.o
In file included from ../src/odbc.cpp:19:
/my_project_path/node_modules/node-addon-api/napi.h:30:6: error: Exception support not detected. Define either NAPI_CPP_EXCEPTIONS or NAPI_DISABLE_CPP_EXCEPTIONS.
    #error Exception support not detected. \
     ^
1 error generated.
make: *** [Release/obj.target/odbc/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /my_project_path/proxy-accelo/node_modules/odbc
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! odbc@2.0.0-3 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the odbc@2.0.0-3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-06-24T14_11_34_214Z-debug.log
```

FYI: I am on Mac OS Mojave (10.14.5).

Any idea what I am not doing right?

Thanks in advance for your time,
Best regards.

**Comment by markdirish** [comment]
Hi @SK0RM ,

This issue has actually been fixed on the master branch of this GitHub, I just haven't had the chance to push to npm yet. I'm at a conference today, so I doubt I will be able to push a new version today, but if you would like to use it in the meantime, you can npm install the github branch and get working!
