### ISSUE TITLE
Cannot find module '...\node_modules\odbc\lib\bindings\napi-v5\odbc.node'

### ISSUE THREAD

**Issue by DanielAlderman** [markdirish/node-odbc#224]
Hello,

I've run into an issue using node-odbc with an old (but LTS) version of node - Version 12.16.1.

The error message is:

```
Error: Cannot find module 'D:\Example\node_modules\odbc\lib\bindings\napi-v5\odbc.node'
Require stack:
- D:\Example\node_modules\odbc\lib\odbc.js
- D:\Example\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Example\node_modules\odbc\lib\odbc.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Example\\node_modules\\odbc\\lib\\odbc.js',
    'D:\\Example\\main.js'
  ]
}
```

Essentially it's trying to pull in the napi-v5 odbc.node file, but if I look in my node_modules folder napi-v6 is present.

How to replicate:

Example Script:
```
const odbc = require('odbc');

function foo() {
    console.log(`This won't ever trigger, because it can't import the module...`);
}

foo();
```

1. `npm init`
2. `npm install odbc`
3. `node main.js`

Can someone please let me know how I can get around this? The old version of Node is built into another piece of software we are using so I am unable to update it.

Please let me know if you require any further information.

Thanks in advance.

**Comment by DanielAlderman** [comment]
I've just done a bit more playing around and if I install ODBC 2.3.6 it appears to work, although it is installing the napi-v3 folder.

I can obviously use this as a work around, but will leave this ticket open should you decide you think any action needs to be taken.
