### ISSUE TITLE
Not able to install odbc in node version > 15[BUG]

### ISSUE THREAD

**Issue by nist729** [markdirish/node-odbc#298]
<!--
**Describe your system**
* `odbc` Package Version: 2.4.2
* ODBC Driver:
* Database Name:
* Database Version:
* Database OS:
* Node.js Version:16.0.0
* Node.js OS:

**Describe the bug**
After adding it to the package.json file, odbc does not get installed and throws an error unless you downgrade your node version to >=15.0.0

**Expected behavior**

**To Reproduce**
Make sure your node version is >15.0.0 and try to add this odbc dependency via whatever package manager you use. I used yarn so I did a yarn install and it threw an error

**Code**
If applicable, add snippets of code to show:

* The offending code:
* Any DEBUG information printed to the terminal:
* Any error information returned from a function call:

**Additional context**

**Comment by kadler** [comment]
Sorry to hear that you're having issues, but unfortunately this bug report is not very helpful. We regularly run node-odbc on node 16 and 18, so it seems specific to your environment or platform and without more detail about the problem, we won't be able to help.

I'm closing this issue, but please re-open if you can update the report with more info such as error messages when installing and platform you are trying to run on (see our issue template for more details).

**Comment by chrjorgensen** [comment]
@kadler @markdirish When the default node version has been set to version 18 (by `update-alternatives --config node`), the installation of `odbc` by npm fails - probably because node version 18 is reporting OS name "os400" instead of "aix" and there is no release for OS400 in this GitHub repo...?

Following is the output when trying to install `odbc` with node version 18 as default:

```
→ npm install odbc
npm ERR! code 1
npm ERR! path /home/NCCJ/odbctest/node_modules/odbc
npm ERR! command failed
npm ERR! command /QOpenSys/pkgs/bin/bash -c -- node-pre-gyp install --fallback-to-build
npm ERR! gmake: Entering directory '/home/NCCJ/odbctest/node_modules/odbc/build'
npm ERR!   CXX(target) Release/obj.target/odbc/src/odbc.o
npm ERR! gmake: Leaving directory '/home/NCCJ/odbctest/node_modules/odbc/build'
npm ERR! Failed to execute '/QOpenSys/pkgs/lib/nodejs18/bin/node /QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/NCCJ/odbctest/node_modules/odbc/lib/bindings/napi-v6/odbc.node --module_name=odbc --module_path=/home/NCCJ/odbctest/node_modules/odbc/lib/bindings/napi-v6 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using @1.0.10
npm ERR! node-pre-gyp info using node@18.12.1 | os400 | ppc64
npm ERR! node-pre-gyp info check checked for "/home/NCCJ/odbctest/node_modules/odbc/lib/bindings/napi-v6/odbc.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/markdirish/node-odbc/releases/download/v2.4.6/odbc-v2.4.6-os400-ppc64-napi-v6.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.6/odbc-v2.4.6-os400-ppc64-napi-v6.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for odbc@2.4.6 and node@18.12.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.6/odbc-v2.4.6-os400-ppc64-napi-v6.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.12.1 | os400 | ppc64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.12.1 | os400 | ppc64
npm ERR! gyp info find Python using Python version 3.6.15 found at "/QOpenSys/pkgs/bin/python3"
npm ERR! gyp info spawn /QOpenSys/pkgs/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/NCCJ/odbctest/node_modules/odbc/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/NCCJ/.cache/node-gyp/18.12.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/NCCJ/.cache/node-gyp/18.12.1',
npm ERR! gyp info spawn args   '-Dnode_exp_file=/QOpenSys/pkgs/lib/nodejs18/include/node/node.exp',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/NCCJ/.cache/node-gyp/18.12.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/NCCJ/odbctest/node_modules/odbc',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.12.1 | os400 | ppc64
npm ERR! gyp info spawn gmake
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/odbc.cpp:22:0:
npm ERR! ../src/odbc.h:37:17: fatal error: sql.h: No such file or directory
npm ERR!  #include <sql.h>
npm ERR!                  ^
npm ERR! compilation terminated.
npm ERR! gmake: *** [odbc.target.mk:140: Release/obj.target/odbc/src/odbc.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `gmake` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System OS400 7.3
npm ERR! gyp ERR! command "/QOpenSys/pkgs/lib/nodejs18/bin/node" "/QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/NCCJ/odbctest/node_modules/odbc/lib/bindings/napi-v6/odbc.node" "--module_name=odbc" "--module_path=/home/NCCJ/odbctest/node_modules/odbc/lib/bindings/napi-v6" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
npm ERR! gyp ERR! cwd /home/NCCJ/odbctest/node_modules/odbc
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/QOpenSys/pkgs/lib/nodejs18/bin/node /QOpenSys/pkgs/lib/nodejs18/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/NCCJ/odbctest/node_modules/odbc/lib/bindings/napi-v6/odbc.node --module_name=odbc --module_path=/home/NCCJ/odbctest/node_modules/odbc/lib/bindings/napi-v6 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/NCCJ/odbctest/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System OS400 7.3
npm ERR! node-pre-gyp ERR! command "/QOpenSys/pkgs/lib/nodejs18/bin/node" "/home/NCCJ/odbctest/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/NCCJ/odbctest/node_modules/odbc
npm ERR! node-pre-gyp ERR! node -v v18.12.1
npm ERR! node-pre-gyp ERR!  -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok
```

And here the output when installing `odbc` using node version 16 as the default:

```
→ npm install odbc

added 61 packages, and audited 62 packages in 6s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by kadler** [comment]
@chrjorgensen nothing to do with Node version, you're missing header files:

```
npm ERR! ../src/odbc.h:37:17: fatal error: sql.h: No such file or directory
npm ERR!  #include <sql.h>
```

You need to install unixODBC-devel package.

**Comment by chrjorgensen** [comment]
@kadler No, this is the fallback of building the binary locally because the prebuilt binary was not found on the GitHub repository:

```
npm ERR! node-pre-gyp info using node@18.12.1 | os400 | ppc64
npm ERR! node-pre-gyp info check checked for "/home/NCCJ/odbctest/node_modules/odbc/lib/bindings/napi-v6/odbc.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/markdirish/node-odbc/releases/download/v2.4.6/odbc-v2.4.6-os400-ppc64-napi-v6.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.6/odbc-v2.4.6-os400-ppc64-napi-v6.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for odbc@2.4.6 and node@18.12.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.6/odbc-v2.4.6-os400-ppc64-napi-v6.tar.gz
```

The binary was not built with the `os400` in the name - it was only built for `aix` which is the platform name returned by node version 16, where node version 18 uses platform name `os400`. So when using node version 18 , no binary is found - which it should... ;-)

My workaround was to change the default node version to 16, install the `odbc` module and change back to node version 18. The `odbc` modules works just fine with node version 18, it just won't install...

**Comment by chrjorgensen** [comment]
This is the output from node version 18:

```
→ /QOpenSys/pkgs/lib/nodejs18/bin/node
Welcome to Node.js v18.12.1.
Type ".help" for more information.
> console.log(process.platform)
os400
```

And the output from node version 16:

```
→ /QOpenSys/pkgs/lib/nodejs16/bin/node
Welcome to Node.js v16.18.1.
Type ".help" for more information.
> console.log(process.platform)
aix
```

I think the solution would be to build a binary named `odbc-v2.4.6-os400-ppc64-napi-v6.tar.gz` and include it in the releases going forward. What do you think?

**Comment by markdirish** [comment]
I am not sure that just renaming the file will do the trick. I can try and see what happens. I also am not sure if I can get it to build nicely on Node.js 18 + node-pre-gyp, I think node-pre-gyp and node-gyp have their own built-in lists of OSes available. Will give it a spin.

**Comment by kadler** [comment]
@chrjorgensen Ohhhhh right. I forgot we have pre-built binaries.

**Comment by markdirish** [comment]
@chrjorgensen I just published a new release, 2.4.7. I built it with Nodejs 18 (to produce `os400` binaries) and with Nodejs 16 (to produce `aix` binaries). It should work to download now!

**Comment by chrjorgensen** [comment]
@markdirish I can confirm that I can now install `odbc` release 2.4.7 in both Nodejs 18 and Nodejs16. Thanks for fixing this!

**Comment by markdirish** [comment]
@chrjorgensen Nice! Because that issue is fixed, and the original issue doesn't have any constructive description of the problem, I am going to close this issue

**Comment by JeffBerman** [comment]
@markdirish Is the plan to keep creating Node 16 binaries of odbc with each release? We're unable to install `odbc` on our Node 16 IBM i system. Thanks!

**Comment by chrjorgensen** [comment]
@JeffBerman This is a closed issue - you're probably better off creating new issues. 😉 

Anyway, according to the commits the current version 2.4.9 requires Node version 18 and above (only LTS versions are supported). If you want to install `odbc` for Node version 16, maybe you could install the previous version `npm i odbc@2.4.8`, which was created when Node version 16 was still a LTS? 🙏 

Or even better - upgrade your Node to a supported (LTS) version... I know, not always easy... 😄

**Comment by kadler** [comment]
@JeffBerman Mark is no longer a maintainer on this package as he left IBM. Node 16 hasn't been supported upstream for over a year and will no longer be supported by this package going forward. As a reminder, this package only supports LTS versions of Node.js that are supported upstream.

If it helps, in the future we can bump the minor version (eg. 2.4.x -> 2.5) when we drop support.
