### ISSUE TITLE
version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by ShowmanStone** [markdirish/node-odbc#360]
**Describe your system**
* `odbc` Package Version:2.4.8
* Node.js Version:14.21.3
* GCC Version:4.8.5
* Node.js OS:centos 7.6

**Describe the bug**
Hi, I just install node14.21.3 then npm install odbc, and got node-odbc@2.4.8 successfully. then i run the connection example and got error:
internal/modules/cjs/loader.js:1173
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/lib/node/nodejs/lib/node_modules/odbc/lib/bindings/napi-v6/odbc.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/usr/local/lib/node/nodejs/lib/node_modules/odbc/lib/odbc.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12) {
  code: 'ERR_DLOPEN_FAILED'
} 

It seems my GCC version is not high enough, but i wonder why i can install successfully with my gcc environment? what can i do to use node-odbc besides upgrade gcc?(upgrade gcc may effect other running applications)

Looking forward to your reply.

**Comment by kadler** [comment]
You'll likely need to rebuild from source since your Linux distribution is older than the one the prebuilt binaries get built on.
