### ISSUE TITLE
Error: `gmake` failed with exit code: 2

### ISSUE THREAD

**Issue by MrTeapot** [markdirish/node-odbc#54]
Hey!

Gettings this error when installing on IBM I:

```
remote: gmake: Entering directory '/container1/project/code/node_modules/odbc/build'
remote:   CXX(target) Release/obj.target/odbc/src/odbc.o
remote: In file included from ../src/odbc.cpp:19:0:
remote: /container1/project/code/node_modules/node-addon-api/napi.h:5:22: fatal error: functional: No such file or directory
remote:  #include <functional>
remote:                       ^
remote: compilation terminated.
remote: gmake: *** [odbc.target.mk:127: Release/obj.target/odbc/src/odbc.o] Error 1
remote: gmake: Leaving directory '/container1/project/code/node_modules/odbc/build'
remote: gyp ERR! build error
remote: gyp ERR! stack Error: `gmake` failed with exit code: 2
remote: gyp ERR! stack     at ChildProcess.onExit (/QOpenSys/pkgs/lib/container1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
remote: gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
remote: gyp ERR! System OS400 7.3
remote: gyp ERR! command "/QOpenSys/pkgs/lib/container1/bin/node" "/QOpenSys/pkgs/lib/container1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
remote: gyp ERR! cwd /container1/project/code/node_modules/odbc
remote: gyp ERR! node -v v10.16.3
remote: gyp ERR! node-gyp -v v3.8.0
remote: gyp ERR! not ok
remote: npm WARN container1-azure@0.0.1 No repository field.
remote: npm WARN container1-azure@0.0.1 No license field.
```

Does anyone know what could be wrong?

**Comment by MrTeapot** [comment]
Turns out I was missing libstdcplusplus-devel
Installed it with yum install libstdcplusplus-devel
